security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        default:
            pattern: ^/
            anonymous: ~

        api:
            pattern: ^/api
            security: false
            stateless: true
