AppBundle\Entity\Client:
    type: entity
    table: client
    repositoryClass: AppBundle\Repository\ClientRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        initiationDate:
            type: datetime
            nullable: true
        terminal:
            type: integer
            nullable: true
        session:
            type: string
            length: 255
            nullable: true
        agent:
            type: string
            length: 255
            nullable: true
        card:
            type: string
            length: 255
            nullable: true
        carrierNumber:
            type: string
            length: 255
            nullable: true
        carrierName:
            type: string
            length: 255
            nullable: false
        carrierFirstName:
            type: string
            length: 255
            nullable: false
        carrierAddress:
            type: string
            length: 255
            nullable: false
        carrierPostalCode:
            type: string
            length: 255
            nullable: true
        carrierTown:
            type: string
            length: 255
            nullable: true
        carrierContractNumber:
            type: string
            nullable: true 
        transactionId:
            type: string
            length: 255
            nullable: true          
